version: "3.8"

services:
  postgres-test:
    image: postgres:15
    container_name: ecommerce_postgres_test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: ecommerce_test
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d ecommerce_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata_test:
