import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AnnounceWithNav } from "./components/AnounceWithNav";
import { AuthProvider } from "./auth-context";
import { createClient } from "@/utlis/supabase/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();
  const {
    data: { session },
  } = await (await supabase).auth.getSession();
  console.log(session);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider initialUser={session?.user ?? null}>
          <AnnounceWithNav />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
