import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AnnounceWithNav } from "./components/AnounceWithNav";
import { AuthProvider } from "./auth-context";
import { createClient } from "@/utlis/supabase/server";
import GoogleOneTap from "./components/GoogleOneTap";
import Script from "next/script";
import Footer from "./components/Footer";
import DisableScrollRestoration from "./components/DisableScroll";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const headersList = await headers();
  const pathname = headersList.get("x-next-pathname") || "";
  const isAdminRoute = pathname.startsWith("/admin");

  const supabase = createClient();
  const {
    data: { user },
  } = await (await supabase).auth.getUser();
  // console.log(session);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script
          src="https://accounts.google.com/gsi/client"
          strategy="afterInteractive"
        />
        <GoogleOneTap />
        <AuthProvider initialUser={user ?? null}>
          {!isAdminRoute && <AnnounceWithNav />}
        </AuthProvider>
        <DisableScrollRestoration />
        {children}
        {modal}
        {!isAdminRoute && <Footer />}
      </body>
    </html>
  );
}
