"use client";

import { motion, AnimatePresence } from "framer-motion";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Announcement } from "./components/Announcement";
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [showAnnouncement, setShowAnnouncement] = useState(true);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <motion.div layout transition={{ duration: 0.6, ease: "easeInOut" }}>
          <AnimatePresence mode="popLayout">
            {showAnnouncement && (
              <Announcement setShow={() => setShowAnnouncement(false)} />
            )}
          </AnimatePresence>

          <Navbar />
        </motion.div>
        {children}
      </body>
    </html>
  );
}
